name: continious-integration-learning
on:
  push:
    branches:
      - main

jobs:
  pre-commit-scans:
    runs-on: ubuntu-latest

    steps:
      - name: Setup java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"

      - name: Checkout code
        uses: actions/checkout@v4

      - name: google formatter check
        run: mvn com.spotify.fmt:fmt-maven-plugin:check

      - name: Gitleaks Scan
        uses: zricethezav/gitleaks-action@v1.3.0
        with:
          args: --path=.

      - name: OSSS Scan
        run: mvn ossindex:audit
        continue-on-error: true

      - name: OWASP Scan
        if: false
        run: mvn org.owasp:dependancy-check-maven:check

      - name: build code and create docker image
        run: mvn clean install docker:build -Dimage.registry=${{vars.CONTAINER_REGISTRY_URL}} -Dimage.tag=$GITHUB_REF_NAME

      # - name : iamge tag
      #   run :  docker tag dnyanyog.org/api-gateway:latest sagargonjare/api_gateway:$GITHUB_REF_NAME

      - name: log in into github registry
        uses: docker/login-action@v2
        with:
          username: ${{vars.DOCKER_REGISTRY_USER}}
          password: ${{secrets.DOCKER_REGISTRY_PASS}}

      - name: push docker image to docker hub
        #  run : docker push ${{vars.CONTAINER_REGISTRY_URL}}/api-gateway:$GITHUB_REF_NAME
        run: |
          CURRENT_FOLDER_NAME=$(basename $(pwd))
          docker push ${{vars.CONTAINER_REGISTRY_URL}}/api-gateway:$GITHUB_REF_NAME
